name: mustachex
description: Mustache Extended
version: 0.0.1
# homepage: https://www.example.com
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  mustache_recase: ^2.0.2
  mustache_template: ">=1.0.0 <2.0.0"
  path: ^1.6.0
  quiver: ^2.1.5
  recase: ^3.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
